### ISSUE TITLE
Create and run script to update database plots

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#164]
This would be useful for after a reprocessing where the days are not processed strictly sequentially.

This could be implemented as a new `ucomp` sub-command: `dbplot`.

#### Tasks

- [x] create script called `ucomp_db_update_wrapper`
- [x] ~~create `ucomp` CLI sub-command~~
- [x] run script after reprocessing: `ucomp script -f production -n ucomp_db_update_wrapper DATES`

> [!NOTE]
> **Time estimate**: This should only take 2-3 hours.

**Comment by mgalloy** [comment]
This has finished. Below are the 1074 nm mission plots with values from the 1.0.1 reprocessing.

![20221109 ucomp 1074 mission backgrounds](https://github.com/NCAR/ucomp-pipeline/assets/713524/c86cc20c-d1f6-46a8-997d-e6f82a12bb83)

![20221109 ucomp 1074 mission centering](https://github.com/NCAR/ucomp-pipeline/assets/713524/83732f1f-700d-438e-b04d-5d5c07eec5ca)

![20221109 ucomp 1074 mission eccentricity](https://github.com/NCAR/ucomp-pipeline/assets/713524/7d86dcb9-2e18-4b0c-b8cd-b88ce3dd7637)

![20221109 ucomp 1074 mission image_scale](https://github.com/NCAR/ucomp-pipeline/assets/713524/81368bd2-d4de-4da1-9589-73f3ff991ecd)

![20221109 ucomp 1074 mission radius-diff](https://github.com/NCAR/ucomp-pipeline/assets/713524/2cbd2a2b-9164-44ff-a227-c23eb1778d96)

![20221109 ucomp 1074 mission vcrosstalk](https://github.com/NCAR/ucomp-pipeline/assets/713524/10d4a05c-41cb-4979-908b-6eacb49577a2)
