### ISSUE TITLE
Add FITS keyword to specify wavelength offset

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#171]
Offset of reported wavelength to get to actual wavelength to correct for drift.

This is the result of the rest wavelength computation with unapplying `WAVOFF`. This work needs to be done after #175.

#### Tasks

- [x] add `RSTMTHD` keyword in LOS velocity extension header, either "model fit" or "image", with comment "rest wavelength computation method"
- [x] add `WAVOFF2` with comment "[nm] offset for center wavelength", e.g., the 1.89 for 1074 nm

#### Questions

- [x] What is the name of the keyword? Comment?

> [!NOTE]
> **Time estimate**: Given a method to find this offset, this should only take 1-2 hours to implement.
