### ISSUE TITLE
Comply with SOLARNET FITS standards

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#202]
[SOLARNET] ([HTML]) is an emerging standard for solar observations that unites ground-based and space-based observations. From the abstract:

> Until the advent of the SOLARNET recommendations, metadata descriptions of Solar observations have only been standardized for space-based observations, but the standards have been mostly within a single space mission at a time, at times with significant differences between different mission standards. In the context of ground-based Solar observations, data has typically not been made freely available to the general research community, resulting in an even greater lack of standards for metadata descriptions. This situation makes it difficult to construct multi-instrument archives/virtual observatories with anything more than the most basic metadata available for searching, as well as making it difficult to write generic software for instrument-agnostic data analysis. This document describes the metadata recommendations developed under the SOLARNET EU project, which aims foster more collaboration and data sharing between both ground-based and space-based Solar observatories. The recommendations will be followed by data pipelines developed under the SOLARNET project, by the Solar Orbiter SPICE pipeline, the SST CHROMIS/CRISP common pipeline SSTRED, and the Alma pipeline for Solar data (SOAP) among others1. These recommendations are meant to function as a common reference to which even existing diverse data sets may be related, for ingestion into solar virtual observatories and for analysis by generic software.

Published UCoMP data files should be SOLARNET compliant.

[SOLARNET]: https://arxiv.org/ftp/arxiv/papers/2011/2011.12139.pdf "SOLARNET Metadata Recommendations for Solar Observations"
[HTML]: https://solarnet-metadata.readthedocs.io/en/latest/

#### Tasks

- [ ] add `SOLARNET` keyword (1 if fully compliant, 0.5 if partially)
- [ ] add `OBS_HDU` for each image extension (not primary)
- [ ] add `DATE-BEG` (same as `DATE-OBS`)
- [ ] add `TIMESYS` with value "UTC"
- [ ] do we need `CRPIXja`, `CRVALia`, `PCi_ja`, and `CDELTia`? Are they the same as the non-"a" version?
- [ ] do we need `CTYPEia='UTC'` and `DATEREF`?
- [ ] add `OBSGEO-X`, `OBSGEO-Y`, and `OBSGEO-Z`: "In principle, the coordinates should be given in ITRF geocentric coordinates. However, for SOLARNET purposes, GPS coordinates are an acceptable proxy."
- [ ] more starting at Section 5...

**Comment by mgalloy** [comment]
By the way, [this is a great paper](https://github.com/NCAR/ucomp-pipeline/files/15043106/precision_effects_solar_image_coordinate_system_fits_WCS_thompson_2010.pdf) about using FITS WCS to specify the spatial coordinates of an image.
