### ISSUE TITLE
Ability to combine movies

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#245]
`ffmpeg` has the ability to combine mp4s into a longer mp4. Sarah wants year or longer movies that combine the daily movies into a single movie.

#### Tasks

- [ ] find the right combination of command line options to concatenate movies, check [this]
- [ ] create IDL wrapper to concatenate a type of mp4 by wave region and product
- [ ] determine desired length of movies
- [ ] create movies

[this]: https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg
