### ISSUE TITLE
Post mask in the wrong location

### ISSUE THREAD

**Issue by detoma** [NCAR/ucomp-pipeline#248]
There are some frames where the post mask appears in the wrong location. 

See for example movies on October 23-35 2022.

| Dates | Times | Fixed with better ESTIMATES | Fixed with restricted search |
| ----- | ----- | --------------------------- | ---------------------------- |
| 20220207 | 012807-013013 | yes | yes |
| 20220208 | 203449-203810 | 203556-203844 still broken, I think original was 203522-204058 were bad; these images are pretty bad | 203736 and 203810 still broken |
| 20220412 | 204734 | yes | yes |
| 20220601 | 003039 | yes | yes |
| 20220709 | 190418 | yes | yes |
| 20220710 | 195345 | yes | yes |
| 20220713 | 191309,191202 ; displayed in average for all data types of 1074 | yes | yes |
| 20220714 | 191851 | yes | yes |
| 20220908 | 202651 | yes | yes |
| 20220914 | 195535 | yes | yes |
| 20220916 | 222107 | yes | yes |
| 20220917 | 203428 | yes | yes |
| 20220918 | 201913, 202020 | yes | yes |
| 20220919 | 201553, 201627 | yes | yes |
| 20220925 | 004910, 014930 | 014930 still broken | yes |
| 20220926 | 212859 | yes | yes |
| 20220928 | 203728 | yes | yes |
| 20220930 | 203903, 204010 | yes | yes |
| 20221007 | 203117, 203151, 203406, 203908 | yes | yes |

#### Tasks

- [x] use a narrower initial guess range *Narrowing the Gaussian line width helps.*
- [x] confirm the initial guess is the correct alignment *The initial guess is not used. Actually, it is used in `ESTIMATES` for Gaussian fit.*
- [x] restrict post search to 180.0 +/- some tolerance
- [x] set to 180.0 if outside of some tolerance

#### Summary

All the current know bad post angles are fixed except for two on 20220208. These images are very poor (see below). Bad post angles are set to 180.0 degrees, so they won't be far off from the correct post angle.

**Comment by detoma** [comment]
Other days when the occulter post is in the wrong location in 1074 movies are:
Oct 7, Oct 17, Oct 22, Oct 23, Oct 24, Oct 25, Oct 26, Oct 28, Nov 9 

Not clear why this problem appears more often late in the mission.

**Comment by mgalloy** [comment]
For 20220207 in 1074, there are two bad images:

- 20220208.012807
- 20220208.013013

The post is slightly off in both images, once to one side and once to the other.

Odds things about those two images:

```
20220208.012807.07.ucomp.1074.l0.fts: removing pol state 1, camera 1, ext 1
20220208.013013.79.ucomp.1074.l0.fts: removing pol state 1, camera 1, ext 14
```

The bad frames for the day:

```
20220207.185333.49.ucomp.656.l0.fts,1,23,3
20220207.205224.43.ucomp.1074.l0.fts,1,5,2
20220207.205224.43.ucomp.1074.l0.fts,1,5,2
20220207.223639.29.ucomp.1079.l0.fts,0,40,2
20220207.224920.07.ucomp.1079.l0.fts,1,14,1
20220208.012807.07.ucomp.1074.l0.fts,1,1,1
20220208.013013.79.ucomp.1074.l0.fts,1,14,1
```

Note: there is a repeated bad frame in the listing for 20220207.205224.

| Raw file | Result |
| -------- | ----- |
| 20220207.185333.49.ucomp.656.l0.fts | bad GBU: spurious Stokes V signal is above threshold (8.0)|
| 20220207.205224.43.ucomp.1074.l0.fts | OK |
| 20220207.223639.29.ucomp.1079.l0.fts | OK |
| 20220207.224920.07.ucomp.1079.l0.fts | bad GBU: the difference of the image with the median is above threshold (1.5) |
| 20220208.012807.07.ucomp.1074.l0.fts | bad post |
| 20220208.013013.79.ucomp.1074.l0.fts | bad post |

**Comment by mgalloy** [comment]
Need to have an epoch for when the occulter became a fixed angle. Focus in 1074 nm.

**Comment by mgalloy** [comment]
Decreasing the line width parameter of the `ESTIMATES` for the Gaussian fit seems to have fixed 20220207.

The `POST_ANG` and `SOLAR_P0` for some problem files on 20220207:

```
20220208.012807.ucomp.1074.l1.p5.fts     195.167   -14.909
20220208.013013.ucomp.1074.l1.p5.fts     195.253   -14.910
```

whereas the `POST_ANG` was 5-6 degrees off before:

```
20220208.012807.ucomp.1074.l1.p5.fts     200.161   -14.909
20220208.013013.ucomp.1074.l1.p5.fts     189.115   -14.910
```

All the 1074 files for the day are groups in a 0.293 degree band where:

``` math
0.258 < (p - p_0 - 180.0) < 0.551
```

where $p$ is `POST_ANG` and $p_0$ is `SOLAR_P0`.

**Comment by mgalloy** [comment]
Note that the initial guess is actually not used. A Gaussian of particular width is fit.

**Comment by mgalloy** [comment]
The above technique did not work for 20221007 — the same files had bad post angles.

**Comment by detoma** [comment]
Let's look at the code together. I thought for COMP we were searching the post around the location given by the initial guess. We know quite well where the post is in UCOMP so we should use that info.

**Comment by mgalloy** [comment]
Adjusting both `estimates[1]` and `estimates[2]` fixes the issues for 20221007 for 1074. All the 1074 files for the day are grouped in a 0.171 degree band:

$$0.785 < (p - p_0 - 180) < 0.956$$

**Comment by mgalloy** [comment]
It works for 20220918 too.

**Comment by mgalloy** [comment]
For 20220208, here are two consecutive images, the first succeeded, the second failed. The solid white line is the data of the profile we are trying to fit. The red line line is the initial guess estimates. The dotted line is the fit. I'm not really sure what the fit is seeing in the 20220208.203556 version. There is no error. It performs 7 iterations, where the maximum number of iterations is 20.

20220208.203522

![20220208 203522 ucomp 1074 distortion p3 fts](https://github.com/NCAR/ucomp-pipeline/assets/713524/fd51c900-2d8b-4eeb-930b-a90d45b02506)

20220208.203556

![20220208 203556 ucomp 1074 distortion p3 fts](https://github.com/NCAR/ucomp-pipeline/assets/713524/e21daf2a-64d2-4e5d-8c78-3ddc5c07989b)

**Comment by mgalloy** [comment]
Reprocessing the test cases with the changes to limit the search angles to a range around 180.0.

**Comment by mgalloy** [comment]
Below are the only two images I know are still broken. Their post angle is adjusted to 180.0 degrees.

![20220208 203736 ucomp 1074 l1 p3 intensity](https://github.com/NCAR/ucomp-pipeline/assets/713524/72d841c3-1ada-42fd-836f-60410ade6835)

![20220208 203810 ucomp 1074 l1 p3 intensity](https://github.com/NCAR/ucomp-pipeline/assets/713524/664b6f85-fa25-4bc1-92d0-bbee8698e96f)

**Comment by mgalloy** [comment]
Just to record some facts from our discussion a while ago:

- The post mask was 60 pixels wide, now it is 70 pixels wide. I can increase if you want it. The initial estimate for finding the post is 10 degrees, though that changes with the fit.
- Results for 20220207 and 20240409 with the current code (70 pixel post mask) and centering annotations in `engineering.latest` on the new development server. See below for centering images.

For 20220207:

![Image](https://github.com/user-attachments/assets/3a0597d4-7740-4db2-8606-5f8046649ae4)

![Image](https://github.com/user-attachments/assets/e8e11e4a-24e0-430f-b434-e7934b48c046)

For 20240409:

![Image](https://github.com/user-attachments/assets/c358fec6-7b44-4574-88ec-fa1f62d9661a)

![Image](https://github.com/user-attachments/assets/ad1824dd-e6d8-4bdc-ae31-0cc3a2c24f30)
