### ISSUE TITLE
Test newly produced distortion coefficients

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#251]
Test @bberkeyU's newly produced distortion coefficients in the pipeline.  This distortion assumes rotation is in the cameras and not the grid, so we distort both cameras to a square, non-rotated grid.   As far as we can tell the new grids look ok.

#### Tasks

- [x] create an IDL save file of the current distortion file format from Ben's netCDF files (it will not be exact because Ben's file has a different number of coefficients)
- [x] replace the current distortion file with the new one
- [x] update distortion applying method to recognize the number of coefficients and correctly apply in each case
- [x] run on test date

#### Questions

- [x] how do I apply the `xCam` and `yCam` arrays to science data?
- [x] `xCam` and `yCam` are 1310720 element arrays, are they row major or column major? i.e., can I just do `reform(xCam, 1280, 1024)`?

#### Summary

When using a good distortion and updating Steve's code to change the assumptions about the image tilts, we got a good fit. Steve assumed the tilt always came from the grid but we know it comes from the cameras.  The new code version does not rotate the ideal grid array to the average of camera rotations.

**Comment by mgalloy** [comment]
I have preliminary results in `process.latest` for 20221118. I am applying the correction incorrectly in same way because there is a large offset in the images.

**Comment by bberkeyU** [comment]
Attaching an L1 image to show the geometry problem.

Unfortunately, the distortion correction didn't work well either, with a fuzzy occulter disk and smeared coronal features.

![20221118 193058 ucomp 1074 l1 p3 iquv](https://github.com/NCAR/ucomp-pipeline/assets/22605316/ba2ba22d-22ff-4975-8d87-f4561c6cbbfb)

**Comment by mgalloy** [comment]
It looks like x and y were swapped, not sure if it happened with the original netCDF creation or when I created the save file. But the new results in `process.latest` are better — than the ones above, and I think from the original distortion.

**Comment by bberkeyU** [comment]
Mike.  That is correct I got my X and Y mixed up.

**Comment by mgalloy** [comment]
Here is the new distortion for the same date/time as above:

![20221118 193058 ucomp 1074 l1 p3 iquv](https://github.com/NCAR/ucomp-pipeline/assets/713524/89bb4a37-2b86-4df5-af0c-8874083ddc85)

And here is the current production version:

![20221118 193058 ucomp 1074 l1 3 iquv](https://github.com/NCAR/ucomp-pipeline/assets/713524/79954448-774f-4eb6-b68a-98fb3e534303)

**Comment by bberkeyU** [comment]
Mike, I produced 2 new sets of distortion coefficients.   It is not clear which is better.  Would it be possible to run one day with both data sets?

Files are copied to /home/mgalloy/software/ucomp-pipeline/resource/distortion

The first set has the filenames distortMap_...... the second distortMap2.....
distortMap_20240327_10006_1074.nc
distortMap_20240327_10009_1074.nc

distortMap2_20240327_10006_1074.nc
distortMap2_20240327_10009_1074.nc

**Comment by mgalloy** [comment]
Results are in `process.distortmap` and `process.distortmap2`.

**Comment by detoma** [comment]
We need to test the latest distortion coefficients given by Ben using the IDL code by applying the distortion to the grid data and look at the difference/ratio.  I also requested a run with intermediate products to further check this out.

**Comment by mgalloy** [comment]
The distortion corrected flat files (which include the distortion grid files) are in the `distortion` directory in `process.distortion/20240330`.

**Comment by bberkeyU** [comment]
@mgalloy What other processing was done to these files? Did we do the X-axis camera flip?

**Comment by mgalloy** [comment]
The full distortion step was done:

- flip RCAM on the x-axis
- apply the distortion
- flip both cameras on the y-axis

**Comment by bberkeyU** [comment]
@mgalloy 
I think I have a better set of distortion coefficients and have copied the save file to:
/home/mgalloy/software/ucomp-pipeline/resource/distortion/dist_coeff_20240330_1074_degree4.sav

Can you reprocess the grid files (ala process.distortion) into process.distortion2 with this new set of coefficients?

**Comment by bberkeyU** [comment]
@mgalloy Based on time stamps It looks like the pipeline finished processing process.distortion2 but I dont see the process.distortion2/20240330/distortion directory.   Could you reprocess this again with the make distortion directory option on.

**Comment by mgalloy** [comment]
I had to process the date, and then run the `distort` command on it. Running now...

**Comment by mgalloy** [comment]
OK, the `distortion` directory in `process.distortion2` is there now.

**Comment by bberkeyU** [comment]
New versions of the IDL code checked into subversion, and new coefficients were copied to dawn.

The IDL code has been cleaned up a bit and I think it might be good to move this code to github.  The two most obvious locations seem to be ucomp-pipeline or ucomp-studies but neither seems perfect.

**Comment by mgalloy** [comment]
The coefficients are in `dist_coeff_20240330_1074_degree3.sav` from yesterday?

I have a `calibration` directory in the `ucomp-pipeline` repo where I am collecting code that produces the artifacts that are used by the pipeline. Right now, there is only a `polarimetric` directory that has a modified version of Steve's code to product demodulation matrices. A parallel directory for distortion would probably be the best place for this code.

**Comment by bberkeyU** [comment]
@mgalloy That is the best distortion as far as I know.

Next steps: Re-run the eclipse data dist_coeff_20240330_1074_degree3.sav with intermediate products so we can check the quality of the data with this distortion compared to the previous one.

**Comment by mgalloy** [comment]
@bberkeyU Should I close this issue, or move it to the 1.1 milestone?

**Comment by bberkeyU** [comment]
My personal should close issue 251.   I am sure we will do a lot more work on distortion throughout the mission, but I dont see any more work on in the short term.

**Comment by detoma** [comment]
Testing the velocity I run into two files processed with the old and new version of the distortion. They are very very different. 

Ben: Can you grab a AIA file on 2024 04 09 and check which orientation looks more consistent with AIA? 

Can Don make a composite for 2024 04 09 with AIA and KCor?

**Comment by jburkepile** [comment]
I will ask Don to make composites. I suggest a 1074 image with an AIA 193 image. We assume the Sun is centered under the occulter. The corona moves in the 1074 images between 18:07 and 19:05.  There is no observer log. Which do we think is has better pointing?

 I will also ask him to make a K-Cor-AIA composite. 

 Don can't use fits images - Adobe illustrator does not accept fits format. He can use 'quicklooks' such as gif, png, etc. I ask him to scale AIA to the pixel size of K-Cor or UCoMP based on the platescale of the instruments.

**Comment by bberkeyU** [comment]
@detoma I have never worked with AIA, but I can try it. Can you elaborate on the differences you see between the old and new distortions and why there is a concern?  I was expecting changes as we found better coefficients.   Is the concern mostly rotation or something else? 

@jburkepile We didn't have the obs fully backup on April 9th. Lisa made notes in an email she sent out to the group.  But the notes dont have (or observatory logs in general) dont tell us anything about how well we are pointing.

**Comment by detoma** [comment]
Ben: do not worry about AIA. We will do it. 

The rotation between the two distortion is very obvious, we need to find out which one gives a better orientation. The eclipse data will be used a lot. 

If there is a motion over the day, this complicates things.

**Comment by detoma** [comment]
I tried a AIA/UCOMP composite using an image at 1905UT from the process.eclipse directory (not sure which distortion has). I did not have code to do it, so I wrote something quickly. Don can do better.
It does not look aligned in the NE, it looks better in then SW.

<img width="1025" alt="Screenshot 2024-07-11 at 1 18 02 PM" src="https://github.com/user-attachments/assets/44435dba-1c53-42b2-8e40-5b7057c61370">

**Comment by bberkeyU** [comment]
@detoma  process. eclispe an old version of the distortion.   I think this was the discropy( python version), but it might be another version of Steves's code I will try to check.

What does the process.hot-pixels-20221125_test version look like?

**Comment by bberkeyU** [comment]
We processed the eclipse data with  3 (or up to 5) versions of the distortion corrections.   The distortion files with filenames that end in .sav were produced with some version of the IDL code.  I think the 1.0.5 releases used the python code (which produced .nc files), but we didnt record the filename in the header.  


process : 1.0.5 [b1417f0] No DISTORTF in the header
process.latest : 1.0.10-dev [bab404f4*] dist_coeff_20240330_1074_degree3.sav
process.4-term : 1.0.10-dev [733f97f4*] dist_coeff_20240330_1074_degree4.sav
process.3-term : 1.0.10-dev [733f97f4*] dist_coeff_20240330_1074_degree4.sav
process.hot-pixels-20240409_test : 1.0.10-dev [b6afa292*] dist_coeff_20240330_1074_degree3.sav
process.intermediate : 1.0.10-dev [c90a89d6*] No DISTORTF in the header
process.eclipse : 1.0.5-dev [e29c733b*] No DISTORTF in the header
process.analytic-gaussian : 1.0.10-dev [b6afa292*] dist_coeff_20240330_1074_degree3.sav

**Comment by mgalloy** [comment]
By the way, this is the current correct distortion files to use for the various time periods? Just the one switch when the instrument was updated in November 2022?

```
[20210526]
distortion_basename          : dist_coeff_20210708_1074.sav

[20221111]
distortion_basename          : dist_coeff_20240330_1074_degree3.sav
```

**Comment by detoma** [comment]
Process.latest has what Ben thinks is the best distortion, correct? I will use that for the AIA alignment

**Comment by bberkeyU** [comment]
For posterity, the process. latest plot uses dist_coeff_20240330_1074_degree3.sav, which uses the IDL code with a 3-degree fit.   

When commuting the distortion coefficients, we assume the tilt in the image grids comes from a camera rotation, not a misalignment in the targets. Therefore, we commented out the section of the code that rotated the ideal-rectilinear target array to the average rotation of the two cameras.
