### ISSUE TITLE
Make thumbnails for images that appear on web

### ISSUE THREAD

**Issue by mgalloy** [NCAR/ucomp-pipeline#263]
Make simplified, smaller thumbnail images with readable text for the website.

#### Tasks

- [x] Make thumbnails for all average level 2 images.
- [x] Make thumbnails for temperature maps images.
- [x] Publish thumbnails in `fullres`.
- [x] Create test thumbnails for 20221018.

#### Questions

- [x] What size should they be? There are hooks to make differently sized images already, but most be an integer divisor of 1280x1024. *The size Don wants is 640x512.*
- [x] What filename should be used? *Add `_thumb` before extension to each GIF and PNG created.*
- [x] Should I put them in `fullres`, or `lowres`? or somewhere else? *Put them in `fullres`.*
- [x] Do they go in the quicklooks zip file? any zip or tarball? *No.*
- [x] What information is OK to not display on thumbnails? Maybe only the colorbar is needed because these are only used on the webpage and the webpage already displays everything else: *just the colorbar and the quantity*
  - the viewer already know it is MLSO UCoMP
  - the viewer already know the date
  - the viewer have selected the wave region in the controls below and it is displayed in the lower left corner of the image
  - the viewer know it is Intensity, Enhanced Intensity, etc. from selecting from the controls below, but the viewer doesn't know the power applied to it
  - the viewer know the min/max from the colorbar, but not the gamma (only useful for Intensity and Enhanced Intensity)

**Comment by mgalloy** [comment]
As best I can tell, these images should appear about what will happen on the website:

<img alt="20240330 ucomp 789 l2 synoptic median peak_intensity_cropped" src="https://github.com/NCAR/ucomp-pipeline/assets/713524/8709923c-51f5-472d-a7e2-5fb7dd15f383" width="340px"/>

<img alt="20240330 ucomp 789 l2 synoptic median enhanced_intensity_cropped" src="https://github.com/NCAR/ucomp-pipeline/assets/713524/95dd6a22-f49f-49e6-a48b-53212a30b5ea" width="340px"/>

<img alt="20240330 ucomp 789 l2 synoptic median line_width_cropped" src="https://github.com/NCAR/ucomp-pipeline/assets/713524/47001ad2-f0e8-4a01-9f25-6731be399ad9" width="340px"/>

<img alt="20240330 ucomp 789 l2 synoptic median los_velocity_cropped" src="https://github.com/NCAR/ucomp-pipeline/assets/713524/12260b7a-9bdb-4722-8939-5c9f53bbf117" width="340px"/>

**Comment by mgalloy** [comment]
The above commit makes progress, but is incomplete in two ways:

- [ ] We only need to make thumbnails for the average level 2 files (this makes thumbnails for all level 2 files).
- [ ] We need to make thumbnails for the temperature maps.

**Comment by mgalloy** [comment]
Why are the 1079 thumbnails not created? Am I missing others?

**Comment by mgalloy** [comment]
The 1079 average files were not created because there were too few 1079 files to create one, hence, no daily level 2 file with thumbnails. Creating an average, even if only a single file, fixes this now.
