### ISSUE TITLE
Draw circle at photosphere and position angle locations in UCoMP quicklook images

### ISSUE THREAD

**Issue by jburkepile** [NCAR/ucomp-pipeline#272]
Draw circle at photosphere and position angle locations in UCoMP quicklook images to make it possible to read off locations of coronal structures from quicklook images. These are drawn in the occulter. Use the KCor quicklook images as a guide. See program `kcor_suncir.pro` by A. Stanger which is in `kcor-pipeline/src/util`.

![20221026_220055_kcor_l2_avg_unsharp_mask_nrgf_v2](https://github.com/NCAR/ucomp-pipeline/assets/18175973/88dd6cfb-dc62-4206-8737-75a8d9a65d1b)

Circle and position angle locations should be in each level 1 UCoMP intensity GIF and level 2 UCoMP PNG quicklook (intensity, doppler, linear polarization, line width, radial and angular azimuth).

Let's name the annotations to be able to take about them:

- exterior angle location dots
- interior angle location dots
- cardinal directions
- radial dots
- central circle of dots
- North up arrow

#### Questions

- [x] The annotations in UCoMP are written in the center of the image. How much of these center angle locations need to be in the center? or should the text annotations be moved? i.e., can I not do the radial dots, central circle of dots, and the North up arrow? how about the cardinal directions? *Just need dots on the photosphere.*
- [x] Should I label some of the exterior location dots with angles because you won't be able to see all of them? i.e., you won't be able to count the number of dots from straight North to determine your angle. *Remove exterior dots.*
- [x] I assume no annotations in the IQUV and IQUV all images? dashboard level 2 images? *Just full size images.*

#### Tasks

- [x] intensity GIFs
- [x] level 2 images
- [x] temperature maps
- [x] small dot every 5 degrees, tick mark every 10 degrees, large tick mark every 30 degrees

**Comment by mgalloy** [comment]
For example, below is a manual first draft.

![20240409 214658 ucomp 1074 l1 p5 intensity gif](https://github.com/NCAR/ucomp-pipeline/assets/713524/81856775-5e5b-4ddb-8b24-6358d6ac7402)

**Comment by jburkepile** [comment]
That looks good Mike. If you could add a fiducial mark at 0, 90, 180 and 270 degrees that would also be helpful.

thanks for getting to this so quickly
joan

**Comment by mgalloy** [comment]
What kind of fiducial mark? Just a larger/elongated tick? a label?

**Comment by detoma** [comment]
Thank you Mike! I like it. It looks good as it is to me. If we want to add an elongated tick, I would do it every 30deg.

**Comment by jburkepile** [comment]
An elongated tick works for me too! Every 30 degrees would be perfect - as Giuliana said above.
thanks!

**Comment by mgalloy** [comment]
Here is an example with minor ticks every 5 degrees, major ticks every 10 degrees, and "fiducial" ticks every 30 degrees.

![20221126 004426 ucomp 1074 l1 p3 intensity gif](https://github.com/NCAR/ucomp-pipeline/assets/713524/b97235b1-5f2c-4ec7-af9f-c0389b0957f8)

**Comment by mgalloy** [comment]
Here are the minor-major-fudicial marks as differing sized squares.

![20221126 004426 ucomp 1074 l1 p3 intensity gif](https://github.com/NCAR/ucomp-pipeline/assets/713524/a0d92f87-6104-4109-96b0-12221c7bbb45)

**Comment by mgalloy** [comment]
Below is the temperature map with the newest version of the grid.

![20240330 ucomp 1074-789-637 daily_temperature](https://github.com/NCAR/ucomp-pipeline/assets/713524/6e2cdd3f-b5cd-45c5-9ac9-13281041fcd6)

**Comment by jburkepile** [comment]
I like the grid and the larger fiducials every 30 deg. Looks good!

**Comment by detoma** [comment]
Let's remove the dots in the outer field. They do not add much information.
