### ISSUE TITLE
Change in GBU criteria

### ISSUE THREAD

**Issue by detoma** [NCAR/ucomp-pipeline#286]
This is part of a bigger issue but the following steps can be easily implemented:

- make the sigma threshold 1.8 instead of 1.5 to avoid labelling bad some good images
- do not use the sigma criteria if fewer than 8 images are available

#### Questions

- [ ] I have changed `gbu_max_stddev_i` from 1.8 to 1.5 for 1074 nm. Do the other wave regions's thresholds need to change?
- [ ] I have a separate `gbu_max_stddev_i` for Q and U, that is currently set to the same as `gbu_max_stddev_i`. Should it be different?

#### Tasks

- [x] change sigma threshold 1.8 to 1.5
- [x] check number of files available for sigma calculation: do not perform check if not enough files
- [ ] check GBU results
