### ISSUE TITLE
Make sure flats/darks are applied to like NUC corrections

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/ucomp-pipeline#32]
Darks and flats should be applied to images with a matching NUC: "normal" or "Offset + gain corrected".

On Feb 23 we ran part of the day with NUC= normal and another part NUC=NUC Offset + gain corrected.  But at least for a couple of the files, the pipeline applied the normal Gain corrected NUC to a file taken with the normal NUC. 

NUC NORMAL: 20220223.194838.72
NUC Offset + gain corrected: 20220223.195343

     RAWFILE = '20220223.194838.72.ucomp.1074.l0.fts' / raw file                     
     RAWEXTS = '1,4     '           / extension(s) used from RAWFILE                 
     RAWDARK1= '20220223.194525.94.ucomp.l0.fts' / raw dark filename used, wt 0.45   
     DARKEXT1=                    6 / ext in 20220223.ucomp.dark.fts used, wt 0.45   
     RAWDARK2= '20220223.195117.87.ucomp.l0.fts' / raw dark filename used, wt 0.55   
     DARKEXT2=                    7 / ext in 20220223.ucomp.dark.fts used, wt 0.55   
     FLATFILE= '20220223.194628.95.ucomp.1074.l0.fts' / name of raw flat file used   
     FLATEXTS= '1       '           / ext(s) in 20220223.194628.95.ucomp.1074.l0.fts 
     MFLATEXT=                  103 / ext in20220223.ucomp.flat.1074.fts used       

     RAWFILE = '20220223.195343.11.ucomp.1074.l0.fts' / raw file
     RAWEXTS = '1,4     '           / extension(s) used from RAWFILE
     RAWDARK1= '20220223.195117.87.ucomp.l0.fts' / raw dark filename used, wt 0.97   
     DARKEXT1=                    7 / ext in 20220223.ucomp.dark.fts used, wt 0.97   
     RAWDARK2= '20220223.210058.49.ucomp.l0.fts' / raw dark filename used, wt 0.03   
     DARKEXT2=                    8 / ext in 20220223.ucomp.dark.fts used, wt 0.03   
     FLATFILE= '20220223.195241.58.ucomp.1074.l0.fts' / name of raw flat file used   
     FLATEXTS= '1       '           / ext(s) in 20220223.195241.58.ucomp.1074.l0.fts 
     MFLATEXT=                  109 / ext in 20220223.ucomp.flat.1074.fts used

#### Questions

- [x] Can `RCAMNUC` and `TCAMNUC` be different? *If a cal file has different `RCAMNUC` and `TCAMNUC` values, then I mark the NUC value for the file specially, so it won't be used. If a science file has differing values, I fail when looking up a dark and flat for it.*

#### Tasks

- [x] create routine to convert NUC value into a NUC index
- [x] save NUC index extension in cached darks/flats and master/flat files
- [x] update `ucomp_calibration::get_dark` and `ucomp_calibration::get_flat` to accept a `nuc` parameter that must match the returned dark or flat
- [x] update `ucomp_l1_apply_dark` and `ucomp_l1_apply_flat` to pass NUC to `::get_dark` and `::get_flat`

**Comment by bberkeyU** [comment]
The NUC value in the header is the camera's feedback after setting the value.  This is read out after the camera setup and stored in a LabVIEW variable until written to the FITS header. 

The only place the observing code sets or reads the NUC is when the UCoMP-controller (maybe a LabVIEW program) starts up and initializes its settings.  The value to set the NUC is pulled from the instrument_config.ini file and is common between both cameras. 

Other camera settings, namely gain and exposure, can be changed while the code is running via recipes, but the NUC is set only at startup.

@mgallloy what are the standard NUC values?  The RCAMNUC listed are the 4 possible 12-bit output values, with a few others for 8bit outputs and RAMP result that replaces the array values with a test pattern.

**Comment by mgalloy** [comment]
Other files to check:

- `20210728.184105.61.ucomp.l0.fts`
- `20211012.211907.91.ucomp.l0.fts`
- `20220223.175101.97.ucomp.l0.fts`

**Comment by mgalloy** [comment]
For 20210728, there were no science files, so NUC consistency is preserved.

**Comment by mgalloy** [comment]
The processing seems to have worked for 20220223. Here are `RAWDARK1`, `RAWDARK2`, `FLTFILE1`, and `FLTFILE2` [for every processed level 1 file for the day](https://github.com/user-attachments/files/24010531/20220223.calfiles-used.txt). Note the NUC changes from "normal" to "Offset + gain corrected" at 19:51:17. All the files before 19:51:17 have dark and flat files from before 19:51:17, and all the files after 19:51:17 have dark and flat files from after 19:51:17. Most notably, for the files right before the change that are no appropriate same-NUC dark and flat files after them, so they are not interpolated:

```
20220223.194730.ucomp.1074.l1.p3.fts
  1  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  2  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  3  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  4  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  5  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  6  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
20220223.194804.ucomp.1074.l1.p3.fts
  1  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  2  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  3  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  4  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  5  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  6  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
20220223.194838.ucomp.1074.l1.p3.fts
  1  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  2  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  3  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  4  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  5  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  -----
  6  20220223.194525.94.ucomp.l0.fts  -----  20220223.194628.95.ucomp.1074.l0.fts  --—-
```

This is a good test for this issue and it looks to be working for days with both "normal" and "Offset + gain corrected" files.

**Comment by mgalloy** [comment]
For 20220826, most of the day is "Offset + gain corrected", but there are some add files:

```
20220826.174400.70.ucomp.l0.fts         dark        Offset + gain corrected  offset + gain  + dark
20220826.174522.95.ucomp.530.l0.fts     sci         Offset + gain corrected  offset + gain  + dark
...
20220826.192729.09.ucomp.l0.fts         dark        Offset + gain corrected  offset + gain  + dark
20220826.192916.43.ucomp.530.l0.fts     sci         Offset + gain corrected  offset + gain  + dark
```

Correctly, for `20220826.174522.95.ucomp.530.l0.fts`, no dark was found. `20220826.192916.43.ucomp.530.l0.fts` was skipped for bad quality. The 2 darks with the odd `TCAMNUC` values were never used for the other science files.

**Comment by mgalloy** [comment]
For 20250323, most of the day is "Offset + gain corrected", but there are 2 odd files:

```
20250323.211728.76.ucomp.l0.fts         dark        Offset + gain corrected  offset + gain  + dark
20250323.211848.75.ucomp.1079.l0.fts    sci         Offset + gain corrected  offset + gain  + dark
```

For `20250323.211848.75.ucomp.1079.l0.fts`, it was rejected in the averaging step because of bad frames. `20250323.211728.76.ucomp.l0.fts` was never used as a dark.
